### ISSUE TITLE
Add Mandarin to Czech react

### ISSUE THREAD

**Issue by chanomkaimuk** [placeTW/discord-bot#80]
Right now `resources/reacts/baltics.json` reacts to Taiwan in Baltic languages and **Baltic country names in Mandarin**.

We should add the Mandarin word (捷克, etc) to the Czech reacts in `resources/reacts/czech.json`.

**Comment by howardt12345** [comment]
Ok you can do it

**Comment by chanomkaimuk** [comment]
I... was going to tag it as `good-first-issue`...

**Comment by howardt12345** [comment]
shibelol

**Comment by chanomkaimuk** [comment]
Closed with #111, thanks @milspectacular
